services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ContaoMemberExtensionBundle\:
        resource: '../src/'
        exclude: '../src/{Model,DependencyInjection,Resources}'
